### ISSUE TITLE
Charm install broken on bionic

### ISSUE THREAD

**Issue by samuelallan72** [canonical/layer-filebeat#113]
With a new build on main at the time of writing, built with charmcraft 2.6.0.

Logs:

```
unit-filebeat-1: 05:19:17 DEBUG unit.filebeat/1.install Successfully installed MarkupSafe-2.0.1 wheel-0.33.6
unit-filebeat-1: 05:19:17 DEBUG unit.filebeat/1.install Looking in links: wheelhouse
unit-filebeat-1: 05:19:17 DEBUG unit.filebeat/1.install Collecting netaddr==0.7.19
unit-filebeat-1: 05:19:18 DEBUG unit.filebeat/1.install Collecting charms.reactive==1.5.2
unit-filebeat-1: 05:19:18 DEBUG unit.filebeat/1.install Collecting pbr==6.0.0
unit-filebeat-1: 05:19:18 DEBUG unit.filebeat/1.install Collecting contextvars==2.4
unit-filebeat-1: 05:19:19 DEBUG unit.filebeat/1.install Collecting PyYAML==5.3.1
unit-filebeat-1: 05:19:19 DEBUG unit.filebeat/1.install Collecting charmhelpers==1.2.1
unit-filebeat-1: 05:19:20 DEBUG unit.filebeat/1.install Collecting typing-extensions==4.1.1
unit-filebeat-1: 05:19:20 WARNING unit.filebeat/1.install Exception:
unit-filebeat-1: 05:19:20 WARNING unit.filebeat/1.install Traceback (most recent call last):
unit-filebeat-1: 05:19:20 WARNING unit.filebeat/1.install   File "/var/lib/juju/agents/unit-filebeat-1/.venv/lib/python3.6/site-packages/pip/_internal/cli/base_command.py",
line 143, in main
unit-filebeat-1: 05:19:20 WARNING unit.filebeat/1.install     status = self.run(options, args)
unit-filebeat-1: 05:19:20 WARNING unit.filebeat/1.install   File "/var/lib/juju/agents/unit-filebeat-1/.venv/lib/python3.6/site-packages/pip/_internal/commands/install.py",
line 318, in run
unit-filebeat-1: 05:19:20 WARNING unit.filebeat/1.install     resolver.resolve(requirement_set)
unit-filebeat-1: 05:19:20 WARNING unit.filebeat/1.install   File "/var/lib/juju/agents/unit-filebeat-1/.venv/lib/python3.6/site-packages/pip/_internal/resolve.py", line 102,
 in resolve
unit-filebeat-1: 05:19:20 WARNING unit.filebeat/1.install     self._resolve_one(requirement_set, req)
unit-filebeat-1: 05:19:20 WARNING unit.filebeat/1.install   File "/var/lib/juju/agents/unit-filebeat-1/.venv/lib/python3.6/site-packages/pip/_internal/resolve.py", line 256,
 in _resolve_one
unit-filebeat-1: 05:19:20 WARNING unit.filebeat/1.install     abstract_dist = self._get_abstract_dist_for(req_to_install)
unit-filebeat-1: 05:19:20 WARNING unit.filebeat/1.install   File "/var/lib/juju/agents/unit-filebeat-1/.venv/lib/python3.6/site-packages/pip/_internal/resolve.py", line 209,
 in _get_abstract_dist_for
unit-filebeat-1: 05:19:20 WARNING unit.filebeat/1.install     self.require_hashes
unit-filebeat-1: 05:19:20 WARNING unit.filebeat/1.install   File "/var/lib/juju/agents/unit-filebeat-1/.venv/lib/python3.6/site-packages/pip/_internal/operations/prepare.py"
, line 298, in prepare_linked_requirement
unit-filebeat-1: 05:19:20 WARNING unit.filebeat/1.install     abstract_dist.prep_for_dist(finder, self.build_isolation)
unit-filebeat-1: 05:19:20 WARNING unit.filebeat/1.install   File "/var/lib/juju/agents/unit-filebeat-1/.venv/lib/python3.6/site-packages/pip/_internal/operations/prepare.py"
, line 100, in prep_for_dist
unit-filebeat-1: 05:19:20 WARNING unit.filebeat/1.install     self.req.load_pyproject_toml()
unit-filebeat-1: 05:19:20 WARNING unit.filebeat/1.install   File "/var/lib/juju/agents/unit-filebeat-1/.venv/lib/python3.6/site-packages/pip/_internal/req/req_install.py", l
ine 428, in load_pyproject_toml
unit-filebeat-1: 05:19:20 WARNING unit.filebeat/1.install     str(self)
unit-filebeat-1: 05:19:20 WARNING unit.filebeat/1.install   File "/var/lib/juju/agents/unit-filebeat-1/.venv/lib/python3.6/site-packages/pip/_internal/pyproject.py", line 43
, in load_pyproject_toml
unit-filebeat-1: 05:19:20 WARNING unit.filebeat/1.install     pp_toml = pytoml.load(f)
unit-filebeat-1: 05:19:20 WARNING unit.filebeat/1.install   File "/var/lib/juju/agents/unit-filebeat-1/.venv/lib/python3.6/site-packages/pip/_vendor/pytoml/parser.py", line
10, in load
unit-filebeat-1: 05:19:20 WARNING unit.filebeat/1.install     return loads(fin.read(), translate=translate, object_pairs_hook=object_pairs_hook, filename=getattr(fin, 'name'
, repr(fin)))
unit-filebeat-1: 05:19:20 WARNING unit.filebeat/1.install   File "/var/lib/juju/agents/unit-filebeat-1/.venv/lib/python3.6/site-packages/pip/_vendor/pytoml/parser.py", line
23, in loads
unit-filebeat-1: 05:19:20 WARNING unit.filebeat/1.install     ast = _p_toml(src, object_pairs_hook=object_pairs_hook)
unit-filebeat-1: 05:19:20 WARNING unit.filebeat/1.install   File "/var/lib/juju/agents/unit-filebeat-1/.venv/lib/python3.6/site-packages/pip/_vendor/pytoml/parser.py", line
352, in _p_toml
unit-filebeat-1: 05:19:20 WARNING unit.filebeat/1.install     s.expect_eof()
unit-filebeat-1: 05:19:20 WARNING unit.filebeat/1.install   File "/var/lib/juju/agents/unit-filebeat-1/.venv/lib/python3.6/site-packages/pip/_vendor/pytoml/parser.py", line
124, in expect_eof
unit-filebeat-1: 05:19:20 WARNING unit.filebeat/1.install     return self._expect(self.consume_eof())
unit-filebeat-1: 05:19:20 WARNING unit.filebeat/1.install   File "/var/lib/juju/agents/unit-filebeat-1/.venv/lib/python3.6/site-packages/pip/_vendor/pytoml/parser.py", line
164, in _expect
unit-filebeat-1: 05:19:20 WARNING unit.filebeat/1.install     raise TomlError('msg', self._pos[0], self._pos[1], self._filename)
unit-filebeat-1: 05:19:20 WARNING unit.filebeat/1.install pip._vendor.pytoml.core.TomlError: /tmp/pip-install-n9z8x9vo/typing-extensions/pyproject.toml(11, 1): msg
unit-filebeat-1: 05:19:20 WARNING unit.filebeat/1.install Traceback (most recent call last):
unit-filebeat-1: 05:19:20 WARNING unit.filebeat/1.install   File "/var/lib/juju/agents/unit-filebeat-1/charm/hooks/install", line 8, in <module>
unit-filebeat-1: 05:19:20 WARNING unit.filebeat/1.install     basic.bootstrap_charm_deps()
unit-filebeat-1: 05:19:20 WARNING unit.filebeat/1.install   File "lib/charms/layer/basic.py", line 226, in bootstrap_charm_deps
unit-filebeat-1: 05:19:20 WARNING unit.filebeat/1.install     env=_get_subprocess_env())
unit-filebeat-1: 05:19:20 WARNING unit.filebeat/1.install   File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
unit-filebeat-1: 05:19:20 WARNING unit.filebeat/1.install     raise CalledProcessError(retcode, cmd)
unit-filebeat-1: 05:19:20 WARNING unit.filebeat/1.install subprocess.CalledProcessError: Command '['/var/lib/juju/agents/unit-filebeat-1/.venv/bin/pip', 'install', '-U', '--
force-reinstall', '--no-index', '--no-cache-dir', '-f', 'wheelhouse', 'netaddr==0.7.19', 'charms.reactive==1.5.2', 'pbr==6.0.0', 'contextvars==2.4', 'PyYAML==5.3.1', 'charmh
elpers==1.2.1', 'typing-extensions==4.1.1', 'Cython==0.29.37', 'immutables==0.19', 'pyaml==21.10.1', 'sniffio==1.2.0', 'Jinja2==3.0.3']' returned non-zero exit status 2.
unit-filebeat-1: 05:19:20 ERROR juju.worker.uniter.operation hook "install" (via explicit, bespoke hook script) failed: exit status 1
unit-filebeat-1: 05:19:20 INFO juju.worker.uniter awaiting error resolution for "install" hook
```

**Comment by samuelallan72** [comment]
This was fixed in layer-basic ( https://github.com/canonical/layer-basic/pull/228 ), so new builds of layer-filebeat will not have this issue. :)
