### ISSUE TITLE
Charm install broken on jammy

### ISSUE THREAD

**Issue by samuelallan72** [canonical/layer-filebeat#114]
With a new build on main at the time of writing, built with charmcraft 2.6.0.

juju debug log:

```
unit-fb-jammy-0: 16:21:09 DEBUG unit.fb-jammy/0.install created virtual environment CPython3.10.12.final.0-64 in 347ms
unit-fb-jammy-0: 16:21:09 DEBUG unit.fb-jammy/0.install   creator CPython3Posix(dest=/var/lib/juju/agents/unit-fb-jammy-0/.venv, clear=False, no_vcs_ignore=False, global=False)
unit-fb-jammy-0: 16:21:09 DEBUG unit.fb-jammy/0.install   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/root/.local/share/virtualenv)
unit-fb-jammy-0: 16:21:09 DEBUG unit.fb-jammy/0.install     added seed packages: pip==22.0.2, setuptools==59.6.0, wheel==0.37.1
unit-fb-jammy-0: 16:21:09 DEBUG unit.fb-jammy/0.install   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
unit-fb-jammy-0: 16:21:11 DEBUG unit.fb-jammy/0.install Looking in links: wheelhouse
unit-fb-jammy-0: 16:21:11 DEBUG unit.fb-jammy/0.install Requirement already satisfied: pip in /var/lib/juju/agents/unit-fb-jammy-0/.venv/lib/python3.10/site-packages (22.0.2)
unit-fb-jammy-0: 16:21:11 DEBUG unit.fb-jammy/0.install Looking in links: wheelhouse
unit-fb-jammy-0: 16:21:11 DEBUG unit.fb-jammy/0.install Requirement already satisfied: setuptools in /var/lib/juju/agents/unit-fb-jammy-0/.venv/lib/python3.10/site-packages (59.6.0)
unit-fb-jammy-0: 16:21:12 DEBUG unit.fb-jammy/0.install Looking in links: wheelhouse
unit-fb-jammy-0: 16:21:12 DEBUG unit.fb-jammy/0.install Processing ./wheelhouse/setuptools_scm-1.17.0.tar.gz
unit-fb-jammy-0: 16:21:12 DEBUG unit.fb-jammy/0.install   Preparing metadata (setup.py): started
unit-fb-jammy-0: 16:21:12 DEBUG unit.fb-jammy/0.install   Preparing metadata (setup.py): finished with status 'done'
unit-fb-jammy-0: 16:21:12 DEBUG unit.fb-jammy/0.install Building wheels for collected packages: setuptools-scm
unit-fb-jammy-0: 16:21:12 DEBUG unit.fb-jammy/0.install   Building wheel for setuptools-scm (setup.py): started
unit-fb-jammy-0: 16:21:13 DEBUG unit.fb-jammy/0.install   Building wheel for setuptools-scm (setup.py): finished with status 'done'
unit-fb-jammy-0: 16:21:13 DEBUG unit.fb-jammy/0.install   Created wheel for setuptools-scm: filename=setuptools_scm-1.17.0-py2.py3-none-any.whl size=17711 sha256=da3053dde74faf7656f3b475c89469bc8e6017c01bc7eb66f684cd0cd8f9f3ac
unit-fb-jammy-0: 16:21:13 DEBUG unit.fb-jammy/0.install   Stored in directory: /root/.cache/pip/wheels/93/b2/63/e62474ea421f1dc32e686cb38d97ff62b254cad53a77a01a83
unit-fb-jammy-0: 16:21:13 DEBUG unit.fb-jammy/0.install Successfully built setuptools-scm
unit-fb-jammy-0: 16:21:13 DEBUG unit.fb-jammy/0.install Installing collected packages: setuptools-scm
unit-fb-jammy-0: 16:21:13 DEBUG unit.fb-jammy/0.install Successfully installed setuptools-scm-1.17.0
unit-fb-jammy-0: 16:21:14 DEBUG unit.fb-jammy/0.install Looking in links: wheelhouse
unit-fb-jammy-0: 16:21:14 DEBUG unit.fb-jammy/0.install Processing ./wheelhouse/MarkupSafe-2.0.1.tar.gz
unit-fb-jammy-0: 16:21:14 DEBUG unit.fb-jammy/0.install   Preparing metadata (setup.py): started
unit-fb-jammy-0: 16:21:14 DEBUG unit.fb-jammy/0.install   Preparing metadata (setup.py): finished with status 'done'
unit-fb-jammy-0: 16:21:14 DEBUG unit.fb-jammy/0.install Processing ./wheelhouse/wheel-0.33.6.tar.gz
unit-fb-jammy-0: 16:21:14 DEBUG unit.fb-jammy/0.install   Preparing metadata (setup.py): started
unit-fb-jammy-0: 16:21:14 DEBUG unit.fb-jammy/0.install   Preparing metadata (setup.py): finished with status 'done'
unit-fb-jammy-0: 16:21:14 DEBUG unit.fb-jammy/0.install Building wheels for collected packages: MarkupSafe, wheel
unit-fb-jammy-0: 16:21:14 DEBUG unit.fb-jammy/0.install   Building wheel for MarkupSafe (setup.py): started
unit-fb-jammy-0: 16:21:15 DEBUG unit.fb-jammy/0.install   Building wheel for MarkupSafe (setup.py): finished with status 'done'
unit-fb-jammy-0: 16:21:15 DEBUG unit.fb-jammy/0.install   Created wheel for MarkupSafe: filename=MarkupSafe-2.0.1-cp310-cp310-linux_x86_64.whl size=25866 sha256=68ebe0b7db51fc4dfb3f44f1db9d3b4a0c1f5cfad469963420a665eef0e916b6
unit-fb-jammy-0: 16:21:15 DEBUG unit.fb-jammy/0.install   Stored in directory: /tmp/pip-ephem-wheel-cache-huviv904/wheels/d9/85/a5/46b90baa7f4dc3b079d2f6a8b8b3d5781d14efc7209c17e6a6
unit-fb-jammy-0: 16:21:15 DEBUG unit.fb-jammy/0.install   Building wheel for wheel (setup.py): started
unit-fb-jammy-0: 16:21:15 DEBUG unit.fb-jammy/0.install   Building wheel for wheel (setup.py): finished with status 'done'
unit-fb-jammy-0: 16:21:15 DEBUG unit.fb-jammy/0.install   Created wheel for wheel: filename=wheel-0.33.6-py2.py3-none-any.whl size=21575 sha256=4ba50f3de6af48ab196c1799bd76f1e14ef6efa4dc0fb78e7c7abb2d54d6e0f6
unit-fb-jammy-0: 16:21:15 DEBUG unit.fb-jammy/0.install   Stored in directory: /tmp/pip-ephem-wheel-cache-huviv904/wheels/68/c0/55/d80118b1c9fec15e47b5e404ece89c923f5626d76a517d2875
unit-fb-jammy-0: 16:21:15 DEBUG unit.fb-jammy/0.install Successfully built MarkupSafe wheel
unit-fb-jammy-0: 16:21:15 DEBUG unit.fb-jammy/0.install Installing collected packages: wheel, MarkupSafe
unit-fb-jammy-0: 16:21:15 DEBUG unit.fb-jammy/0.install   Attempting uninstall: wheel
unit-fb-jammy-0: 16:21:15 DEBUG unit.fb-jammy/0.install     Found existing installation: wheel 0.37.1
unit-fb-jammy-0: 16:21:15 DEBUG unit.fb-jammy/0.install     Uninstalling wheel-0.37.1:
unit-fb-jammy-0: 16:21:15 DEBUG unit.fb-jammy/0.install       Successfully uninstalled wheel-0.37.1
unit-fb-jammy-0: 16:21:15 DEBUG unit.fb-jammy/0.install Successfully installed MarkupSafe-2.0.1 wheel-0.33.6
unit-fb-jammy-0: 16:21:16 DEBUG unit.fb-jammy/0.install Looking in links: wheelhouse
unit-fb-jammy-0: 16:21:16 DEBUG unit.fb-jammy/0.install Processing ./wheelhouse/Jinja2-3.0.3.tar.gz
unit-fb-jammy-0: 16:21:16 DEBUG unit.fb-jammy/0.install   Preparing metadata (setup.py): started
unit-fb-jammy-0: 16:21:16 DEBUG unit.fb-jammy/0.install   Preparing metadata (setup.py): finished with status 'done'
unit-fb-jammy-0: 16:21:16 DEBUG unit.fb-jammy/0.install Processing ./wheelhouse/PyYAML-5.3.1.tar.gz
unit-fb-jammy-0: 16:21:16 DEBUG unit.fb-jammy/0.install   Preparing metadata (setup.py): started
unit-fb-jammy-0: 16:21:17 DEBUG unit.fb-jammy/0.install   Preparing metadata (setup.py): finished with status 'done'
unit-fb-jammy-0: 16:21:17 DEBUG unit.fb-jammy/0.install Processing ./wheelhouse/contextvars-2.4.tar.gz
unit-fb-jammy-0: 16:21:17 DEBUG unit.fb-jammy/0.install   Preparing metadata (setup.py): started
unit-fb-jammy-0: 16:21:17 DEBUG unit.fb-jammy/0.install   Preparing metadata (setup.py): finished with status 'done'
unit-fb-jammy-0: 16:21:17 DEBUG unit.fb-jammy/0.install Processing ./wheelhouse/netaddr-0.7.19.tar.gz
unit-fb-jammy-0: 16:21:17 DEBUG unit.fb-jammy/0.install   Preparing metadata (setup.py): started
unit-fb-jammy-0: 16:21:17 DEBUG unit.fb-jammy/0.install   Preparing metadata (setup.py): finished with status 'done'
unit-fb-jammy-0: 16:21:17 DEBUG unit.fb-jammy/0.install Processing ./wheelhouse/charms.reactive-1.5.2.tar.gz
unit-fb-jammy-0: 16:21:17 DEBUG unit.fb-jammy/0.install   Preparing metadata (setup.py): started
unit-fb-jammy-0: 16:21:18 DEBUG unit.fb-jammy/0.install   Preparing metadata (setup.py): finished with status 'done'
unit-fb-jammy-0: 16:21:18 DEBUG unit.fb-jammy/0.install Processing ./wheelhouse/typing_extensions-4.1.1.tar.gz
unit-fb-jammy-0: 16:21:18 DEBUG unit.fb-jammy/0.install   Installing build dependencies: started
unit-fb-jammy-0: 16:21:20 DEBUG unit.fb-jammy/0.install   Installing build dependencies: finished with status 'error'
unit-fb-jammy-0: 16:21:20 WARNING unit.fb-jammy/0.install   error: subprocess-exited-with-error
unit-fb-jammy-0: 16:21:20 WARNING unit.fb-jammy/0.install
unit-fb-jammy-0: 16:21:20 WARNING unit.fb-jammy/0.install   × pip subprocess to install build dependencies did not run successfully.
unit-fb-jammy-0: 16:21:20 WARNING unit.fb-jammy/0.install   │ exit code: 1
unit-fb-jammy-0: 16:21:20 WARNING unit.fb-jammy/0.install   ╰─> [3 lines of output]
unit-fb-jammy-0: 16:21:20 WARNING unit.fb-jammy/0.install       Looking in links: wheelhouse
unit-fb-jammy-0: 16:21:20 WARNING unit.fb-jammy/0.install       ERROR: Could not find a version that satisfies the requirement flit_core<4,>=3.4 (from versions: none)
unit-fb-jammy-0: 16:21:20 WARNING unit.fb-jammy/0.install       ERROR: No matching distribution found for flit_core<4,>=3.4
unit-fb-jammy-0: 16:21:20 WARNING unit.fb-jammy/0.install       [end of output]
unit-fb-jammy-0: 16:21:20 WARNING unit.fb-jammy/0.install
unit-fb-jammy-0: 16:21:20 WARNING unit.fb-jammy/0.install   note: This error originates from a subprocess, and is likely not a problem with pip.
unit-fb-jammy-0: 16:21:20 WARNING unit.fb-jammy/0.install error: subprocess-exited-with-error
unit-fb-jammy-0: 16:21:20 WARNING unit.fb-jammy/0.install
unit-fb-jammy-0: 16:21:20 WARNING unit.fb-jammy/0.install × pip subprocess to install build dependencies did not run successfully.
unit-fb-jammy-0: 16:21:20 WARNING unit.fb-jammy/0.install │ exit code: 1
unit-fb-jammy-0: 16:21:20 WARNING unit.fb-jammy/0.install ╰─> See above for output.
unit-fb-jammy-0: 16:21:20 WARNING unit.fb-jammy/0.install
unit-fb-jammy-0: 16:21:20 WARNING unit.fb-jammy/0.install note: This error originates from a subprocess, and is likely not a problem with pip.
unit-fb-jammy-0: 16:21:20 WARNING unit.fb-jammy/0.install Traceback (most recent call last):
unit-fb-jammy-0: 16:21:20 WARNING unit.fb-jammy/0.install   File "/var/lib/juju/agents/unit-fb-jammy-0/charm/hooks/install", line 8, in <module>
unit-fb-jammy-0: 16:21:20 WARNING unit.fb-jammy/0.install     basic.bootstrap_charm_deps()
unit-fb-jammy-0: 16:21:20 WARNING unit.fb-jammy/0.install   File "/var/lib/juju/agents/unit-fb-jammy-0/charm/lib/charms/layer/basic.py", line 224, in bootstrap_charm_deps
unit-fb-jammy-0: 16:21:20 WARNING unit.fb-jammy/0.install     check_call([pip, 'install', '-U', reinstall_flag, '--no-index',
unit-fb-jammy-0: 16:21:20 WARNING unit.fb-jammy/0.install   File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
unit-fb-jammy-0: 16:21:20 WARNING unit.fb-jammy/0.install     raise CalledProcessError(retcode, cmd)
unit-fb-jammy-0: 16:21:20 WARNING unit.fb-jammy/0.install subprocess.CalledProcessError: Command '['/var/lib/juju/agents/unit-fb-jammy-0/.venv/bin/pip', 'install', '-U', '--force-reinstall', '--no-index', '--no-cache-dir', '-f', 'wheelhouse', 'Jinja2==3.0.3', 'PyYAML==5.3.1', 'contextvars==2.4', 'netaddr==0.7.19', 'charms.reactive==1.5.2', 'typing-extensions==4.1.1', 'immutables==0.19', 'Cython==0.29.37', 'sniffio==1.2.0', 'pbr==6.0.0', 'pyaml==21.10.1', 'charmhelpers==1.2.1']' returned non-zero exit status 1.
unit-fb-jammy-0: 16:21:20 ERROR juju.worker.uniter.operation hook "install" (via explicit, bespoke hook script) failed: exit status 1
unit-fb-jammy-0: 16:21:20 INFO juju.worker.uniter awaiting error resolution for "install" hook
```

and then a bit later as it continues to retry:

```
unit-fb-jammy-0: 16:27:56 DEBUG unit.fb-jammy/0.install Reading package lists...
unit-fb-jammy-0: 16:27:56 DEBUG unit.fb-jammy/0.install Building dependency tree...
unit-fb-jammy-0: 16:27:56 DEBUG unit.fb-jammy/0.install Reading state information...
unit-fb-jammy-0: 16:27:56 DEBUG unit.fb-jammy/0.install 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
unit-fb-jammy-0: 16:27:58 DEBUG unit.fb-jammy/0.install Looking in links: wheelhouse
unit-fb-jammy-0: 16:27:58 DEBUG unit.fb-jammy/0.install Requirement already satisfied: pip in /var/lib/juju/agents/unit-fb-jammy-0/.venv/lib/python3.10/site-packages (22.0.2)
unit-fb-jammy-0: 16:27:58 DEBUG unit.fb-jammy/0.install Looking in links: wheelhouse
unit-fb-jammy-0: 16:27:58 DEBUG unit.fb-jammy/0.install Requirement already satisfied: setuptools in /var/lib/juju/agents/unit-fb-jammy-0/.venv/lib/python3.10/site-packages (59.6.0)
unit-fb-jammy-0: 16:27:59 DEBUG unit.fb-jammy/0.install Looking in links: wheelhouse
unit-fb-jammy-0: 16:27:59 DEBUG unit.fb-jammy/0.install Requirement already satisfied: setuptools-scm in /var/lib/juju/agents/unit-fb-jammy-0/.venv/lib/python3.10/site-packages (1.17.0)
unit-fb-jammy-0: 16:28:00 DEBUG unit.fb-jammy/0.install Looking in links: wheelhouse
unit-fb-jammy-0: 16:28:00 DEBUG unit.fb-jammy/0.install Processing ./wheelhouse/wheel-0.33.6.tar.gz
unit-fb-jammy-0: 16:28:00 DEBUG unit.fb-jammy/0.install   Preparing metadata (setup.py): started
unit-fb-jammy-0: 16:28:00 DEBUG unit.fb-jammy/0.install   Preparing metadata (setup.py): finished with status 'done'
unit-fb-jammy-0: 16:28:00 DEBUG unit.fb-jammy/0.install Processing ./wheelhouse/MarkupSafe-2.0.1.tar.gz
unit-fb-jammy-0: 16:28:00 DEBUG unit.fb-jammy/0.install   Preparing metadata (setup.py): started
unit-fb-jammy-0: 16:28:01 DEBUG unit.fb-jammy/0.install   Preparing metadata (setup.py): finished with status 'done'
unit-fb-jammy-0: 16:28:01 DEBUG unit.fb-jammy/0.install Building wheels for collected packages: wheel, MarkupSafe
unit-fb-jammy-0: 16:28:01 DEBUG unit.fb-jammy/0.install   Building wheel for wheel (setup.py): started
unit-fb-jammy-0: 16:28:01 DEBUG unit.fb-jammy/0.install   Building wheel for wheel (setup.py): finished with status 'done'
unit-fb-jammy-0: 16:28:01 DEBUG unit.fb-jammy/0.install   Created wheel for wheel: filename=wheel-0.33.6-py2.py3-none-any.whl size=21575 sha256=17ce64f49d1f7251c2b27e9ad9ffb5aef521dfcc2141c7f7b2679ee28e931be3
unit-fb-jammy-0: 16:28:01 DEBUG unit.fb-jammy/0.install   Stored in directory: /tmp/pip-ephem-wheel-cache-cqn6bz3a/wheels/68/c0/55/d80118b1c9fec15e47b5e404ece89c923f5626d76a517d2875
unit-fb-jammy-0: 16:28:01 DEBUG unit.fb-jammy/0.install   Building wheel for MarkupSafe (setup.py): started
unit-fb-jammy-0: 16:28:02 DEBUG unit.fb-jammy/0.install   Building wheel for MarkupSafe (setup.py): finished with status 'done'
unit-fb-jammy-0: 16:28:02 DEBUG unit.fb-jammy/0.install   Created wheel for MarkupSafe: filename=MarkupSafe-2.0.1-cp310-cp310-linux_x86_64.whl size=25863 sha256=d9387b9634aacf2204cad424cf429f85f74510d8535c0ef6770610850feb0331
unit-fb-jammy-0: 16:28:02 DEBUG unit.fb-jammy/0.install   Stored in directory: /tmp/pip-ephem-wheel-cache-cqn6bz3a/wheels/d9/85/a5/46b90baa7f4dc3b079d2f6a8b8b3d5781d14efc7209c17e6a6
unit-fb-jammy-0: 16:28:02 DEBUG unit.fb-jammy/0.install Successfully built wheel MarkupSafe
unit-fb-jammy-0: 16:28:02 DEBUG unit.fb-jammy/0.install Installing collected packages: wheel, MarkupSafe
unit-fb-jammy-0: 16:28:02 DEBUG unit.fb-jammy/0.install   Attempting uninstall: wheel
unit-fb-jammy-0: 16:28:02 DEBUG unit.fb-jammy/0.install     Found existing installation: wheel 0.33.6
unit-fb-jammy-0: 16:28:02 DEBUG unit.fb-jammy/0.install     Uninstalling wheel-0.33.6:
unit-fb-jammy-0: 16:28:02 DEBUG unit.fb-jammy/0.install       Successfully uninstalled wheel-0.33.6
unit-fb-jammy-0: 16:28:02 DEBUG unit.fb-jammy/0.install   Attempting uninstall: MarkupSafe
unit-fb-jammy-0: 16:28:02 DEBUG unit.fb-jammy/0.install     Found existing installation: MarkupSafe 2.0.1
unit-fb-jammy-0: 16:28:02 DEBUG unit.fb-jammy/0.install     Uninstalling MarkupSafe-2.0.1:
unit-fb-jammy-0: 16:28:02 DEBUG unit.fb-jammy/0.install       Successfully uninstalled MarkupSafe-2.0.1
unit-fb-jammy-0: 16:28:02 DEBUG unit.fb-jammy/0.install Successfully installed MarkupSafe-2.0.1 wheel-0.33.6
unit-fb-jammy-0: 16:28:03 DEBUG unit.fb-jammy/0.install Looking in links: wheelhouse
unit-fb-jammy-0: 16:28:03 DEBUG unit.fb-jammy/0.install Processing ./wheelhouse/PyYAML-5.3.1.tar.gz
unit-fb-jammy-0: 16:28:03 DEBUG unit.fb-jammy/0.install   Preparing metadata (setup.py): started
unit-fb-jammy-0: 16:28:03 DEBUG unit.fb-jammy/0.install   Preparing metadata (setup.py): finished with status 'done'
unit-fb-jammy-0: 16:28:03 DEBUG unit.fb-jammy/0.install Processing ./wheelhouse/Jinja2-3.0.3.tar.gz
unit-fb-jammy-0: 16:28:03 DEBUG unit.fb-jammy/0.install   Preparing metadata (setup.py): started
unit-fb-jammy-0: 16:28:04 DEBUG unit.fb-jammy/0.install   Preparing metadata (setup.py): finished with status 'done'
unit-fb-jammy-0: 16:28:04 DEBUG unit.fb-jammy/0.install Processing ./wheelhouse/charms.reactive-1.5.2.tar.gz
unit-fb-jammy-0: 16:28:04 DEBUG unit.fb-jammy/0.install   Preparing metadata (setup.py): started
unit-fb-jammy-0: 16:28:04 DEBUG unit.fb-jammy/0.install   Preparing metadata (setup.py): finished with status 'done'
unit-fb-jammy-0: 16:28:04 DEBUG unit.fb-jammy/0.install Processing ./wheelhouse/typing_extensions-4.1.1.tar.gz
unit-fb-jammy-0: 16:28:04 DEBUG unit.fb-jammy/0.install   Installing build dependencies: started
unit-fb-jammy-0: 16:28:07 DEBUG unit.fb-jammy/0.install   Installing build dependencies: finished with status 'error'
unit-fb-jammy-0: 16:28:07 WARNING unit.fb-jammy/0.install   error: subprocess-exited-with-error
unit-fb-jammy-0: 16:28:07 WARNING unit.fb-jammy/0.install
unit-fb-jammy-0: 16:28:07 WARNING unit.fb-jammy/0.install   × pip subprocess to install build dependencies did not run successfully.
unit-fb-jammy-0: 16:28:07 WARNING unit.fb-jammy/0.install   │ exit code: 1
unit-fb-jammy-0: 16:28:07 WARNING unit.fb-jammy/0.install   ╰─> [3 lines of output]
unit-fb-jammy-0: 16:28:07 WARNING unit.fb-jammy/0.install       Looking in links: wheelhouse
unit-fb-jammy-0: 16:28:07 WARNING unit.fb-jammy/0.install       ERROR: Could not find a version that satisfies the requirement flit_core<4,>=3.4 (from versions: none)
unit-fb-jammy-0: 16:28:07 WARNING unit.fb-jammy/0.install       ERROR: No matching distribution found for flit_core<4,>=3.4
unit-fb-jammy-0: 16:28:07 WARNING unit.fb-jammy/0.install       [end of output]
unit-fb-jammy-0: 16:28:07 WARNING unit.fb-jammy/0.install
unit-fb-jammy-0: 16:28:07 WARNING unit.fb-jammy/0.install   note: This error originates from a subprocess, and is likely not a problem with pip.
unit-fb-jammy-0: 16:28:07 WARNING unit.fb-jammy/0.install error: subprocess-exited-with-error
unit-fb-jammy-0: 16:28:07 WARNING unit.fb-jammy/0.install
unit-fb-jammy-0: 16:28:07 WARNING unit.fb-jammy/0.install × pip subprocess to install build dependencies did not run successfully.
unit-fb-jammy-0: 16:28:07 WARNING unit.fb-jammy/0.install │ exit code: 1
unit-fb-jammy-0: 16:28:07 WARNING unit.fb-jammy/0.install ╰─> See above for output.
unit-fb-jammy-0: 16:28:07 WARNING unit.fb-jammy/0.install
unit-fb-jammy-0: 16:28:07 WARNING unit.fb-jammy/0.install note: This error originates from a subprocess, and is likely not a problem with pip.
unit-fb-jammy-0: 16:28:07 WARNING unit.fb-jammy/0.install Traceback (most recent call last):
unit-fb-jammy-0: 16:28:07 WARNING unit.fb-jammy/0.install   File "/var/lib/juju/agents/unit-fb-jammy-0/charm/hooks/install", line 8, in <module>
unit-fb-jammy-0: 16:28:07 WARNING unit.fb-jammy/0.install     basic.bootstrap_charm_deps()
unit-fb-jammy-0: 16:28:07 WARNING unit.fb-jammy/0.install   File "/var/lib/juju/agents/unit-fb-jammy-0/charm/lib/charms/layer/basic.py", line 224, in bootstrap_charm_deps
unit-fb-jammy-0: 16:28:07 WARNING unit.fb-jammy/0.install     check_call([pip, 'install', '-U', reinstall_flag, '--no-index',
unit-fb-jammy-0: 16:28:07 WARNING unit.fb-jammy/0.install   File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
unit-fb-jammy-0: 16:28:07 WARNING unit.fb-jammy/0.install     raise CalledProcessError(retcode, cmd)
unit-fb-jammy-0: 16:28:07 WARNING unit.fb-jammy/0.install subprocess.CalledProcessError: Command '['/var/lib/juju/agents/unit-fb-jammy-0/.venv/bin/pip', 'install', '-U', '--force-reinstall', '--no-index', '--no-cache-dir', '-f', 'wheelhouse', 'PyYAML==5.3.1', 'Jinja2==3.0.3', 'charms.reactive==1.5.2', 'typing-extensions==4.1.1', 'Cython==0.29.37', 'charmhelpers==1.2.1', 'sniffio==1.2.0', 'contextvars==2.4', 'immutables==0.19', 'pbr==6.0.0', 'netaddr==0.7.19', 'pyaml==21.10.1']' returned non-zero exit status 1.

```

**Comment by samuelallan72** [comment]
Confirming that the same fix from https://github.com/canonical/layer-filebeat/issues/112#issuecomment-2247163221 fixes it for jammy too.  I build the charm on jammy.
